#!/bin/bash
#run this script before the slipScript to use the default world and slipperiness level
#list of all layouts
WORLDS="complicated_noGaps office simple_maze base_square half_square small_office quarter_maze three_hallways triangle cafe blocks meeting_room circles half_half weird_shapes cubicles simple_offices just_blocks apartment long_hallway"
#put back name of default world in launch file
sed -i -e "s/\/worlds\/.*\.world/\/worlds\/complicated_noGaps\.world/g" ~/catkin_ws/src/turtlebot3_simulations/turtlebot3_gazebo/launch/turtlebot3_empty_world.launch
for WORLDNAME in $WORLDS; do #loop over worlds
  #change stddev of laser noise back to default value (0.1) in world file
  sed -i -e "s/<mu>.*<\/mu> <!--slip-->/<mu>0.1<\/mu> <!--slip-->/g" ~/catkin_ws/src/turtlebot3_simulations/turtlebot3_gazebo/worlds/$WORLDNAME.world
  sed -i -e "s/<mu2>.*<\/mu2> <!--slip-->/<mu2>0.1<\/mu2> <!--slip-->/g" ~/catkin_ws/src/turtlebot3_simulations/turtlebot3_gazebo/worlds/$WORLDNAME.world
  #make sure laser noise is 0
  sed -i -e "s/<stddev>.*<\/stddev> <!--changehere-->/<stddev>0\.0<\/stddev> <!--changehere-->/g" ~/catkin_ws/src/turtlebot3_simulations/turtlebot3_gazebo/worlds/$WORLDNAME.world
done
